spring.application.name=AcadLink
server.port=8080

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/Acadlink
spring.datasource.username=postgres
spring.datasource.password=Support@2525
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# JWT
app.jwt.secret=VotreCleSecreteTresLongueEtComplexePourJWTAcadLink2024AuMoins256Bits
app.jwt.expiration-ms=86400000

# File upload
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB
